
package com.itheima.crm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.crm.itheima.com/")
public interface CustomerService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "regist", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.RegistResponse")
    public void regist(
            @WebParam(name = "arg0", targetNamespace = "")
                    Customer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomersToDecidedzone", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.AssignCustomersToDecidedzone")
    @ResponseWrapper(localName = "assignCustomersToDecidedzoneResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.AssignCustomersToDecidedzoneResponse")
    public void assignCustomersToDecidedzone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<Integer> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerListHasAssociation", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindCustomerListHasAssociation")
    @ResponseWrapper(localName = "findCustomerListHasAssociationResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindCustomerListHasAssociationResponse")
    public List<Customer> findCustomerListHasAssociation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFixedAreaIdByAddress", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindFixedAreaIdByAddress")
    @ResponseWrapper(localName = "findFixedAreaIdByAddressResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindFixedAreaIdByAddressResponse")
    public String findFixedAreaIdByAddress(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerListNotAssociation", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindCustomerListNotAssociation")
    @ResponseWrapper(localName = "findCustomerListNotAssociationResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindCustomerListNotAssociationResponse")
    public List<Customer> findCustomerListNotAssociation();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itheima.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "upateType", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.UpateType")
    @ResponseWrapper(localName = "upateTypeResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.UpateTypeResponse")
    public void upateType(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.itheima.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.LoginResponse")
    public Customer login(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

}
